# OpenNMT parameters for docaligned dataset

params:
  optimizer: GradientDescentOptimizer
  learning_rate: 1.0
  param_init: 0.1
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_rate: 0.5
  start_decay_steps: 33559 # start after 8 epochs
  decay_steps: 4195 #decy after 1 epoch
  beam_width: 10
  maximum_iterations: 250

train:
  batch_size: 32
  bucket_width: 1
  save_checkpoints_steps: 500
  keep_checkpoint_max: 1
  save_summary_steps: 50
  train_steps: 50338  # 12 epochs: with n=134233 and batch=32
  maximum_features_length: 70
  maximum_labels_length: 70
  sample_buffer_size: 134233  # Consider setting this to the training dataset size.

eval:
  eval_delay: 1800  # Every 0.5 hours
  batch_size: 8 # my changes
  external_evaluators: BLEU

infer:
  batch_size: 16
