model_dir: discourse-embellishment/models/model_sentence_complexify_300d_adam_lr-1

data:
    train_features_file: discourse-embellishment/data/wikilarge.train.simple
    train_labels_file: discourse-embellishment/data/wikilarge.train.complex
    eval_features_file: discourse-embellishment/data/wikilarge.valid.simple
    eval_labels_file: discourse-embellishment/data/wikilarge.valid.complex
    source_words_vocabulary: discourse-embellishment/data/wikilarge.vocab.simple
    target_words_vocabulary: discourse-embellishment/data/wikilarge.vocab.complex
    source_chars_vocabulary: discourse-embellishment/data/wikilarge.vocab.char.simple
    target_chars_vocabulary: discourse-embellishment/data/wikilarge.vocab.char.complex
    word_embeddings: discourse-embellishment/glove/glove.6B.300d.txt

